# Generated by Django 4.2.27 on 2025-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_category_unique_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
