# Generated by Django 4.2.27 on 2026-01-02 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0005_recurringtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
