# Generated by Django 4.2.27 on 2026-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
