# Generated by Django 4.2.27 on 2026-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_userprofile_has_seen_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking')], default='Cash', max_length=50),
        ),
    ]
