# Generated by Django 4.2.27 on 2026-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex color code, e.g. #FF0000', max_length=7),
        ),
    ]
