# Generated by Django 4.2.27 on 2026-01-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
