# Generated by Django 4.2.27 on 2026-02-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_alter_category_limit_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount in Base Currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='income',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount in Base Currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='income',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount in Base Currency'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='currency',
            field=models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Exchange Rate'),
        ),
    ]
