# Generated by Django 4.2.27 on 2026-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_expense_base_amount_expense_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='unique_expense',
        ),
        migrations.RemoveConstraint(
            model_name='income',
            name='unique_income',
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'amount', 'currency', 'description', 'category'), name='unique_expense'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'amount', 'currency', 'source'), name='unique_income'),
        ),
    ]
