# Generated by Django 4.2.27 on 2026-02-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_savingsgoal_goalcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcontribution',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contribution', to='expenses.expense'),
        ),
    ]
