# Generated by Django 4.2.27 on 2026-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_goalcontribution_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='duration',
            field=models.CharField(default='YEARLY', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_drip_email_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('PLUS', 'Plus'), ('PRO', 'Pro')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(fields=('tier', 'duration'), name='unique_plan_tier_duration'),
        ),
    ]
