# Generated by Django 4.2.27 on 2026-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_add_monthly_billing_and_drip_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
