# Generated by Django 4.2.27 on 2026-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_userprofile_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
