# Generated by Django 4.2.27 on 2026-03-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_userprofile_expiry_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-tag', max_length=50, verbose_name='Icon'),
        ),
    ]
