# Generated by Django 4.2.27 on 2026-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_investment',
            field=models.BooleanField(default=False, verbose_name='Treat as Investment / Exclude from Expenses.'),
        ),
    ]
