# Generated by Django 4.2.27 on 2026-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0033_setup_default_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('INVESTMENT', 'Investment Account'), ('OTHER', 'Other')], default='BANK', max_length=20, verbose_name='Account Type'),
        ),
    ]
