# Generated by Django 4.2.27 on 2026-03-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_alter_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_investment',
        ),
    ]
