# Generated by Django 4.2.27 on 2026-03-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_remove_category_is_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transfers_out', to='expenses.account', verbose_name='From Account'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transfers_in', to='expenses.account', verbose_name='To Account'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer')], max_length=10, verbose_name='Transaction Type'),
        ),
    ]
