# Generated by Django 4.2.27 on 2026-03-19 12:28

from django.db import migrations, models


def remove_duplicate_recurring(apps, schema_editor):
    """Keep only the oldest (lowest pk) of each duplicate set."""
    RecurringTransaction = apps.get_model('expenses', 'RecurringTransaction')
    seen = set()
    to_delete = []
    for rt in RecurringTransaction.objects.order_by('id'):
        key = (rt.user_id, rt.transaction_type, rt.amount, rt.currency, rt.description, rt.frequency, rt.start_date)
        if key in seen:
            to_delete.append(rt.id)
        else:
            seen.add(key)
    if to_delete:
        RecurringTransaction.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_add_recurring_transfer_type'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_recurring, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.UniqueConstraint(fields=('user', 'transaction_type', 'amount', 'currency', 'description', 'frequency', 'start_date'), name='unique_recurring_transaction'),
        ),
    ]
