# Generated by Django 4.2.27 on 2026-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_deduplicate_recurring_transactions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='expenses_tr_user_id_5e28dc_idx',
        ),
        migrations.AddField(
            model_name='transfer',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount in Base Currency'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15, verbose_name='Exchange Rate'),
        ),
    ]
