# Generated by Django 4.2.27 on 2026-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0038_remove_transfer_expenses_tr_user_id_5e28dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('INVESTMENT', 'Investment Account'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('OTHER', 'Other')], default='BANK', max_length=20, verbose_name='Account Type'),
        ),
    ]
