# Generated by Django 4.2.27 on 2026-03-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0039_alter_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcontribution',
            name='expense',
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contributions', to='expenses.account', verbose_name='From Account'),
        ),
    ]
