# Generated by Django 4.2.27 on 2026-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0040_remove_goalcontribution_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL for redirection when clicked', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RECURRING', 'Recurring Transaction'), ('ANALYTICS', 'AI Analytics/Insights'), ('MILESTONE', 'Financial Milestone'), ('SYSTEM', 'System/Subscription Alert')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.CharField(blank=True, help_text="Used for deduplication (same slug shouldn't repeat in a month)", max_length=255, null=True),
        ),
    ]
