# Generated by Django 4.2.27 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0043_subscriptionplan_razorpay_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_at_cycle_end',
            field=models.BooleanField(default=False),
        ),
    ]
